{
  config,
  lib,
  pkgs,
  #pkgs-stable,
  #pkgs-last-stable,
  inputs,
  ...
}:
{
  # List packages installed in unstable system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    atuin
    alacritty-graphics
    appimage-run
    base16-shell-preview
    base16-universal-manager
    bat
    btop
    delta
    docker
    dysk
    eza
    git
    gh
    helix
    killall
    kdePackages.qtstyleplugin-kvantum
    libsForQt5.qtstyleplugin-kvantum
    libreoffice
    libsForQt5.qt5ct
    qt6Packages.qt6ct
    localsend
    mangohud
    micro
    mpv
    neovim
    nil
    nh
    wineWowPackages.stable
    webp-pixbuf-loader
    unityhub
    xwayland
    xwayland-satellite
    yazi
    zed-editor
  ];
}
